### ISSUE TITLE
Something went wrong, please try running the script again

### ISSUE THREAD

**Issue by vors** [PrateekKumarSingh/PSCognitiveService#1]
Cool project!

Unfortunately, get this error message all the time

```
PS C:\> "owershell is is fun" | Invoke-SpellCheck -ShowErrors
Something went wrong, please try running the script again
```

There are a couple of things I want to mention
- This error is not actionable. I tried run it few times. What's next? I cannot google it. I tried use `-Verbose` option. Are my keys not good? Is service down? Bug in the module? What should I do?
- To make it actionable error message needs more details. Maybe more output with `-Verbose` to understand the context.
- This is especially discouraging, when you encounter it on the very first try (like me).

**Comment by 4c74356b41** [comment]
I've created PR to fix this (hopefully)

**Comment by PrateekKumarSingh** [comment]
There was a wrong reference to API URL for Invoke-SpellCheck Function , which was Identified by @4c74356b41 and fixed, Moreover, I've added some code to the module in order to add verbosity while handling errors making them more actionable now.
Download the updated module from - Https://github.com/PrateekKumarSingh/ProjectOxford/blob/master/ProjectOxford.psm1
